name: ci-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright:
    name: ${{ matrix.browser }} on ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, macos-12]
        browser: [chrome, firefox, webkit]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm install
      - run: npm run test:${{ matrix.browser }}
        env:
          STANDARD: ${{ secrets.STANDARD }}
          PASSWORD: ${{ secrets.PASSWORD }}
